### ISSUE TITLE
Example data?

### ISSUE THREAD

**Issue by azohra** [xiaoxinghu/repauto#8]
Hey! 

Just finished the SelniumConf webcast and I love what you guys are doing. Any chance you could upload a sample project for those of us looking to test out how this tool works. I ask because I cannot get my own files to work and it seems like others are also having issues.

**Comment by xiaoxinghu** [comment]
@tk8817 We found that the syncing is always problematic, one of the reason is that it has lots of the legacy code from the very beginning. so we are working on a new version that will resolve most of the problems and make it easier to setup. Before that, the best way to get your data into it is through the API. Take a look at the [wiki](https://github.com/xiaoxinghu/repauto/wiki/API).

**Comment by azohra** [comment]
Thanks @xiaoxinghu , I missed that in the wiki earlier. This tool has the potential to revolutionize our reporting and I am looking forward to getting it up and running. 

If you guys have features / fixes in mind but are short on time, please post them as issues / pr's here and my team would be happy to assist. Love what you are trying to accomplish.

**Comment by azohra** [comment]
@xiaoxinghu I have a developer joining my team who I believe would be well suited to assist in the development of Repauto. Are you guys planning to publish a new version any time soon? Do you require assistance on any specific parts of the application?

**Comment by xiaoxinghu** [comment]
@tk8817 The new Repauto needs time to be designed properly before it faces the public. At this stage I think it's better to keep it closed in order to make the design consistent. The current version of Repauto works well with it's RESTFul API. We use it internally in our company. I will push hot fixes occasionally. Besides, The new Repauto is also going to be RESTFul based, so if you build up your input now, I think it should be very easy to migrate later. Oh, if you find any design problems in the APIs please file issues, it will help us to design better APIs for the new version.
